config/routes.rb
Rails.application.routes.draw do
  default_url_options :only_path => true

  namespace :api do
    resources :days do
      collection do
        post 'commit'
      end
    end
  end

  resources :days

  root to: 'days#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  include Rails.application.routes.url_helpers

  scope :with_text, -> { where.not(text: '') }
  def value
    2
  end
end

app/controllers/api/days_controller.rb
module Api
  class DaysController < ApplicationController
    require 'open-uri'

    before_action :find_day, only: [:show]

    def index
      search = params[:search] || '_'
      @days = Day.with_text.where( 'LOWER(text) LIKE ?', "%" + search.downcase + "%" ).order(date: :desc)

      render json: @days.to_json({ methods: [:value] }), status: 200
    end

    def show
      render json: @day.to_json({ methods: [:value] }), status: 200
    end

    def update
      @day = Day.find params[:id]

      @day.update_attributes(
        text: params[:text]
      ) if params[:text].present?

      render json: @day, status: 200
    end

    def commit
      Day.with_text.each do |day|
        File.write("./export/#{day.date}.md", day.text)
      end
      system "cd export && git add . && git status && git commit -m 'update' && git push upstream master"
    end

    private
    def find_day
      parsed_date = Date.strptime(params[:id], "%m-%d-%Y")
      @day = Day.find_or_create_by(date: parsed_date)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def index;end

  def show;end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/days/index.html.erb
<heatmap-component></heatmap-component>

app/views/days/show.html.erb
<show-page></show-page>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarkdownCalendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'vue_app' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=2.0, user-scalable=yes">
  </head>

  <body>
    <div class="container-fluid" id="app">
      <h1>
        <%= link_to root_path do %>
          <%= image_tag "markdown.png", class:"markdown-title" %>
        <% end %>
        <%= link_to 'push', commit_api_days_path, method: :post, remote: true, class:'btn btn-primary mt-2 float-right' %>
      </h1>

      <%= yield %>
    </div>
  </body>
</html>